version: "2"

run:
  timeout: 5m

linters:
  enable:
    - revive
    - unused
    - prealloc
  disable:
    - errcheck

  settings:
    revive:
      severity: warning
      rules:
        - name: unused-parameter
          severity: warning

severity:
    default: warning

