{
 "title": "go-libp2p Host Addresses",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(up,instance)" } },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Reachable Addrs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_host_addrs_reachable{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ipv}}, {{transport}}"
    }
   ]
  },
  {
   "title": "Unreachable Addrs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_host_addrs_unreachable{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ipv}}, {{transport}}"
    }
   ]
  },
  {
   "title": "Unknown Reachability Addrs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_host_addrs_unknown{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{ipv}}, {{transport}}"
    }
   ]
  }
 ]
}