{
 "title": "go-libp2p Identify",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Pushes triggered",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(libp2p_identify_identify_pushes_triggered_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{trigger}}"
    }
   ]
  },
  {
   "title": "Identify Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{dir}}"
    }
   ]
  },
  {
   "title": "Outgoing Address Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_identify_addrs_count{instance=~\"$instance\"}",
     "legendFormat": "address count"
    }
   ]
  },
  {
   "title": "Outgoing Protocols Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_identify_protocols_count{instance=~\"$instance\"}",
     "legendFormat": "protocols count"
    }
   ]
  },
  {
   "title": "Identify Push Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(libp2p_identify_identify_push_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{dir}}"
    }
   ]
  },
  {
   "title": "Incoming Address Count (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(libp2p_identify_addrs_received_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(libp2p_identify_addrs_received_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(libp2p_identify_addrs_received_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    }
   ]
  },
  {
   "title": "Incoming Protocols Count (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(libp2p_identify_protocols_received_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(libp2p_identify_protocols_received_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(libp2p_identify_protocols_received_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "New Connections: Push Support",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(libp2p_identify_conn_push_support_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{support}}"
    }
   ]
  }
 ]
}