name: 'Bug Report'
description: 'Report a bug in go-libp2p.'
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this bug report!
        Please make sure to include *all* relevant information.
        * What you were doing when you experienced the bug.
        * Any error messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
        * When possible, steps to reliably produce the bug.

  - type: textarea
    id: version-info
    attributes:
      label: Version Information
      description: Insert the output of `go list -m all` HERE
