name: 'Documentation Issue'
description: 'Report missing/erroneous documentation, propose new documentation, report broken links, etc.'
labels: ['documentation']

body:
  - type: input
    id: location
    attributes:
      label: "Location"
      description: "In the case of missing/erroneous documentation, where is the error? If possible, a link/url would be great!"

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the documentation issue."
    validations:
      required: true

