name: 'Feature'
description: 'Suggest a new feature in go-libp2p.'
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: >
        Note: If you'd like to suggest an idea related to libp2p but not specifically related to the Go implementation, please file an issue at https://github.com/libp2p/specs instead. Even better, create a new topic on the forums (https://discuss.libp2p.io).
    

  - type: textarea
    validations:
      required: true
    attributes:
        label: 'What problem are you trying to solve?'
        description: 'Describe the problem you are trying to solve.'
        placeholder: "When requesting a _feature_, please be sure to include:
        * Your motivation. Why do you need the feature?
        * How the feature should work.
        
        Please try to be as specific and concrete as possible."
