name: Markdown Links Check

on:
    push: [master]
    pull_request: [master]
    schedule:
      # runs once in a couple of days at 9am
      - cron: '0 9 */2 * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          # for removing any false positives
          config-file: .github/workflows/markdown-links-config.json
