package mixnet

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/mixnet/ces"
	"github.com/libp2p/go-libp2p/mixnet/circuit"
)

func TestVisualProof_MixnetBehavior(t *testing.T) {
	report := []string{
		"# Mixnet Visual Proof",
		"",
		"This file is generated by `go test ./mixnet -run TestVisualProof_MixnetBehavior -v`.",
		"",
	}

	report = append(report, proofCESReconstruction(t)...)
	report = append(report, proofCircuitRebuild(t)...)
	report = append(report, proofHopVisibility(t)...)

	reportPath := "VISUAL_PROOF.md"
	if err := os.WriteFile(reportPath, []byte(strings.Join(report, "\n")), 0o644); err != nil {
		t.Fatalf("write proof report: %v", err)
	}
	t.Logf("visual proof written to %s", reportPath)
}

func proofCESReconstruction(t *testing.T) []string {
	t.Helper()

	cfg := &ces.Config{
		HopCount:         3,
		CircuitCount:     10,
		Compression:      "gzip",
		ErasureThreshold: 7,
	}
	pipeline := ces.NewPipeline(cfg)
	handler := newProofDestinationHandler(pipeline, cfg.ErasureThreshold)

	plaintext := []byte(strings.Repeat("mixnet-proof-payload-", 64))
	compressed, err := pipeline.Compressor().Compress(plaintext)
	if err != nil {
		t.Fatalf("compress plaintext: %v", err)
	}
	encrypted, keyData, err := encryptSessionPayload(compressed)
	if err != nil {
		t.Fatalf("encrypt session payload: %v", err)
	}
	shards, err := pipeline.Sharder().Shard(encrypted)
	if err != nil {
		t.Fatalf("shard encrypted payload: %v", err)
	}

	subsetIndexes := []int{0, 1, 3, 4, 6, 7, 9}
	for _, idx := range subsetIndexes {
		var shardKeyData []byte
		if shards[idx].Index == 0 {
			shardKeyData = keyData
		}
		handler.AddShard("proof-session", shards[idx], shardKeyData, len(shards))
	}

	reconstructed, err := handler.TryReconstruct("proof-session")
	if err != nil {
		t.Fatalf("reconstruct from 70%% shard subset: %v", err)
	}
	if !bytes.Equal(reconstructed, plaintext) {
		t.Fatal("reconstructed payload does not match original plaintext")
	}

	belowThreshold := newProofDestinationHandler(pipeline, cfg.ErasureThreshold)
	for _, idx := range subsetIndexes[:6] {
		var shardKeyData []byte
		if shards[idx].Index == 0 {
			shardKeyData = keyData
		}
		belowThreshold.AddShard("below-threshold", shards[idx], shardKeyData, len(shards))
	}
	if _, err := belowThreshold.TryReconstruct("below-threshold"); err == nil {
		t.Fatal("expected reconstruction failure below threshold")
	}

	plainMarker := plaintext[:16]
	encryptedShardEvidence := true
	for _, idx := range subsetIndexes {
		if bytes.Contains(shards[idx].Data, plainMarker) {
			encryptedShardEvidence = false
			break
		}
	}
	if !encryptedShardEvidence {
		t.Fatal("found plaintext marker in CES shards")
	}

	plainHash := sha256.Sum256(plaintext)
	reconHash := sha256.Sum256(reconstructed)
	samplePrefixLen := 24
	if len(shards[subsetIndexes[0]].Data) < samplePrefixLen {
		samplePrefixLen = len(shards[subsetIndexes[0]].Data)
	}

	return []string{
		"## CES Threshold And Integrity Proof",
		"",
		"| Property | Observed Value |",
		"| --- | --- |",
		fmt.Sprintf("| Total shards produced | %d |", len(shards)),
		fmt.Sprintf("| Reconstruction threshold | %d of %d shards |", cfg.ErasureThreshold, cfg.CircuitCount),
		fmt.Sprintf("| Successful subset used | %v |", subsetIndexes),
		fmt.Sprintf("| Below-threshold subset size | %d shards |", len(subsetIndexes[:6])),
		fmt.Sprintf("| Plaintext SHA-256 | `%s` |", hex.EncodeToString(plainHash[:])),
		fmt.Sprintf("| Reconstructed SHA-256 | `%s` |", hex.EncodeToString(reconHash[:])),
		fmt.Sprintf("| Sample encrypted shard prefix | `%s` |", hex.EncodeToString(shards[subsetIndexes[0]].Data[:samplePrefixLen])),
		fmt.Sprintf("| Plaintext marker absent from sampled shards | `%t` |", encryptedShardEvidence),
		"",
		"Result: reconstruction succeeded with exactly 70% of shards and failed below threshold; reconstructed data matched byte-for-byte.",
		"",
	}
}

func proofCircuitRebuild(t *testing.T) []string {
	t.Helper()

	mgr := circuit.NewCircuitManager(&circuit.CircuitConfig{
		HopCount:     1,
		CircuitCount: 3,
	})

	relays := []circuit.RelayInfo{
		{PeerID: peer.ID("relay-a")},
		{PeerID: peer.ID("relay-b")},
		{PeerID: peer.ID("relay-c")},
		{PeerID: peer.ID("relay-spare")},
	}
	circuits, err := mgr.BuildCircuits(nil, peer.ID("destination"), relays)
	if err != nil {
		t.Fatalf("build circuits: %v", err)
	}
	for _, c := range circuits {
		if err := mgr.ActivateCircuit(c.ID); err != nil {
			t.Fatalf("activate circuit %s: %v", c.ID, err)
		}
	}

	failed := circuits[0]
	mgr.MarkCircuitFailed(failed.ID)
	usedByActive := make(map[peer.ID]bool)
	for _, c := range circuits[1:] {
		for _, p := range c.Peers {
			usedByActive[p] = true
		}
	}
	usedByFailed := make(map[peer.ID]bool)
	for _, p := range failed.Peers {
		usedByFailed[p] = true
	}
	rebuilt, err := mgr.RebuildCircuit(failed.ID)
	if err != nil {
		t.Fatalf("rebuild failed circuit: %v", err)
	}
	if rebuilt == nil || len(rebuilt.Peers) != 1 {
		t.Fatal("rebuilt circuit is invalid")
	}
	if usedByFailed[rebuilt.Peers[0]] {
		t.Fatalf("rebuilt circuit reused failed relay %s", rebuilt.Peers[0])
	}
	if usedByActive[rebuilt.Peers[0]] {
		t.Fatalf("rebuilt circuit reused active relay %s", rebuilt.Peers[0])
	}
	if err := mgr.ActivateCircuit(rebuilt.ID); err != nil {
		t.Fatalf("activate rebuilt circuit: %v", err)
	}
	if mgr.ActiveCircuitCount() != 3 {
		t.Fatalf("expected 3 active circuits after rebuild, got %d", mgr.ActiveCircuitCount())
	}

	return []string{
		"## Circuit Rebuild Proof",
		"",
		"| Property | Observed Value |",
		"| --- | --- |",
		fmt.Sprintf("| Failed circuit ID | `%s` |", failed.ID),
		fmt.Sprintf("| Failed circuit peers | `%v` |", failed.Peers),
		fmt.Sprintf("| Rebuilt circuit ID | `%s` |", rebuilt.ID),
		fmt.Sprintf("| Rebuilt circuit peers | `%v` |", rebuilt.Peers),
		fmt.Sprintf("| Active circuits after rebuild | %d |", mgr.ActiveCircuitCount()),
		"",
		"Result: the failed circuit was replaced with relay peers not present in the failed circuit or any still-active circuit, and the active circuit count returned to the full configured count.",
		"",
	}
}

func proofHopVisibility(t *testing.T) []string {
	t.Helper()

	source := peer.ID("origin-source")
	hops := []peer.ID{
		peer.ID("relay-entry"),
		peer.ID("relay-middle"),
		peer.ID("relay-exit"),
	}
	dest := peer.ID("destination-final")
	sourceStr := source.String()
	destStr := dest.String()
	payload := []byte("PAYLOAD::" + strings.Repeat("hop-secrecy-", 24))
	hopKeys := [][]byte{
		bytes.Repeat([]byte{0x11}, 32),
		bytes.Repeat([]byte{0x22}, 32),
		bytes.Repeat([]byte{0x33}, 32),
	}

	encodedShard, err := EncodePrivacyShard(payload, PrivacyShardHeader{
		SessionID:   []byte("privacy-session"),
		ShardIndex:  0,
		TotalShards: 3,
		HasKeys:     false,
	})
	if err != nil {
		t.Fatalf("encode privacy shard: %v", err)
	}
	if bytes.Contains(encodedShard, []byte(destStr)) {
		t.Fatal("privacy shard header leaked destination")
	}
	if bytes.Contains(encodedShard, []byte(sourceStr)) {
		t.Fatal("privacy shard header leaked source")
	}

	c := &circuit.Circuit{Peers: hops}
	encrypted, err := encryptOnion(payload, c, dest, hopKeys)
	if err != nil {
		t.Fatalf("encrypt onion: %v", err)
	}

	layer1Plain, err := decryptHopPayload(hopKeys[0], encrypted)
	if err != nil {
		t.Fatalf("decrypt layer 1: %v", err)
	}
	layer1Final, layer1Next, layer1Inner, err := parseProofHopPayload(layer1Plain)
	if err != nil {
		t.Fatalf("parse layer 1: %v", err)
	}

	layer2Plain, err := decryptHopPayload(hopKeys[1], layer1Inner)
	if err != nil {
		t.Fatalf("decrypt layer 2: %v", err)
	}
	layer2Final, layer2Next, layer2Inner, err := parseProofHopPayload(layer2Plain)
	if err != nil {
		t.Fatalf("parse layer 2: %v", err)
	}

	layer3Plain, err := decryptHopPayload(hopKeys[2], layer2Inner)
	if err != nil {
		t.Fatalf("decrypt layer 3: %v", err)
	}
	layer3Final, layer3Next, layer3Payload, err := parseProofHopPayload(layer3Plain)
	if err != nil {
		t.Fatalf("parse layer 3: %v", err)
	}

	if layer1Final || layer1Next != hops[1].String() {
		t.Fatalf("entry hop visibility mismatch: final=%t next=%s", layer1Final, layer1Next)
	}
	if layer2Final || layer2Next != hops[2].String() {
		t.Fatalf("middle hop visibility mismatch: final=%t next=%s", layer2Final, layer2Next)
	}
	if !layer3Final || layer3Next != dest.String() {
		t.Fatalf("exit hop visibility mismatch: final=%t next=%s", layer3Final, layer3Next)
	}

	plainMarker := payload[:16]
	if bytes.Contains(layer1Plain, []byte(destStr)) || bytes.Contains(layer2Plain, []byte(destStr)) {
		t.Fatal("intermediate hop plaintext leaked final destination")
	}
	if bytes.Contains(layer1Plain, []byte(sourceStr)) || bytes.Contains(layer2Plain, []byte(sourceStr)) || bytes.Contains(layer3Plain, []byte(sourceStr)) {
		t.Fatal("hop plaintext leaked source identity")
	}
	if bytes.Contains(layer1Plain, plainMarker) || bytes.Contains(layer2Plain, plainMarker) {
		t.Fatal("intermediate hop plaintext exposed application payload")
	}
	if !bytes.Equal(layer3Payload, payload) {
		t.Fatal("exit hop did not recover the original payload")
	}

	return []string{
		"## Hop Visibility Proof",
		"",
		"| Hop | `isFinal` | Visible next hop / destination | Source visible in decrypted layer? | Final destination visible in decrypted layer? | Payload readable at this hop? |",
		"| --- | --- | --- | --- | --- | --- |",
		fmt.Sprintf("| Entry relay | `%t` | `%s` | `%t` | `%t` | `%t` |", layer1Final, layer1Next, bytes.Contains(layer1Plain, []byte(sourceStr)), bytes.Contains(layer1Plain, []byte(destStr)), bytes.Contains(layer1Plain, plainMarker)),
		fmt.Sprintf("| Middle relay | `%t` | `%s` | `%t` | `%t` | `%t` |", layer2Final, layer2Next, bytes.Contains(layer2Plain, []byte(sourceStr)), bytes.Contains(layer2Plain, []byte(destStr)), bytes.Contains(layer2Plain, plainMarker)),
		fmt.Sprintf("| Exit relay | `%t` | `%s` | `%t` | `%t` | `%t` |", layer3Final, layer3Next, bytes.Contains(layer3Plain, []byte(sourceStr)), bytes.Contains(layer3Plain, []byte(destStr)), bytes.Equal(layer3Payload, payload)),
		"",
		fmt.Sprintf("Privacy shard header leaked source? `%t`", bytes.Contains(encodedShard, []byte(sourceStr))),
		"",
		fmt.Sprintf("Privacy shard header leaked destination? `%t`", bytes.Contains(encodedShard, []byte(destStr))),
		"",
		"Result: entry and middle relays only recovered the immediate next hop; the exit relay was the first point where the final destination became visible. None of the decrypted hop layers contained the origin identifier.",
		"",
	}
}

func newProofDestinationHandler(pipeline *ces.CESPipeline, threshold int) *DestinationHandler {
	return &DestinationHandler{
		pipeline:    pipeline,
		shardBuf:    make(map[string][]*ces.Shard),
		totalShards: make(map[string]int),
		timers:      make(map[string]*time.Timer),
		sessions:    make(map[string]chan []byte),
		keys:        make(map[string]sessionKey),
		inboundCh:   make(chan string, 1),
		threshold:   threshold,
		timeout:     time.Minute,
		dataCh:      make(chan []byte, 1),
		stopCh:      make(chan struct{}),
	}
}

func parseProofHopPayload(plaintext []byte) (bool, string, []byte, error) {
	if len(plaintext) < 3 {
		return false, "", nil, fmt.Errorf("plaintext too short")
	}
	nextLen := int(binary.LittleEndian.Uint16(plaintext[1:3]))
	if len(plaintext) < 3+nextLen {
		return false, "", nil, fmt.Errorf("invalid next-hop length")
	}
	return plaintext[0] == 1, string(plaintext[3 : 3+nextLen]), plaintext[3+nextLen:], nil
}
