version: '3.7'

services:
  node0:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=0
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=08011240d6d74dad01dc4aeb034ce9c32142a40972691b1d171d7442c29215f9020f56b3c4ee96554835459549f83edd68142959e4e5825b9c17033df87466e04df67c15
      - MIXNET_PEERS=12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.10
    ports:
      - "4001:4001"
      - "8080:8080"

  node1:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=1
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=08011240980ed9331d236ff123efdbca94596819468e7bfa2cfb201b017d2855fe13b37bf3be7eb69ca28d9b2d4f04a8418d82ee39f5b5d50e4648f950400b9c2e15ad1c
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.11
    ports:
      - "4002:4001"
      - "8081:8080"

  node2:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=2
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=08011240b11eacf962cf894a3209449a41659b0464bf034c1c7a99843dbc2f9526c726879b69978b436dc0573149b3354dad34f189dd651e5e7034c80e708fe675362306
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.12
    ports:
      - "4003:4001"
      - "8082:8080"

  node3:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=3
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=08011240ff14308b95525473cde96570320f4e1296ce29e1590424058309e5b7d37804ac4bb7b04c9529e6e345155fbfed57165108b494ce70993b3ac511866c5c301eee
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.13
    ports:
      - "4004:4001"
      - "8083:8080"

  node4:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=4
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=08011240ee3e25eb82942754837276f733733f8250f1ecbca4ccc74f0bb859a67f2f8ac17d8b3d0216332b72c27c8d5a4df68087e26dc36dd528607894b0449763881b3b
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.14
    ports:
      - "4005:4001"
      - "8084:8080"

  node5:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=5
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=08011240b09a56b2e8e94c1f048b610d6d86e04e0d48fc81fd2bc5ca85aca31b51cd833632b42114014bdf73d6401c13083f7931e204fa896ebe205c5a38c4a503cb1f8d
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.15
    ports:
      - "4006:4001"
      - "8085:8080"

  node6:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=6
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=080112403c8d8f3dd473d38e07f1cc9f50893539f68eb340f5e8c4528242d67d62e29c813f0c00dc779c4e098836cc65e4bdc3fa66599ea09159a937f21b7eeb904f785d
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.16
    ports:
      - "4007:4001"
      - "8086:8080"

  node7:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=7
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=080112402cf92de255b8d9c0edc3c6dba2cd017e9ff0958248c492454c6e8c572bed1ba00a5ed9dca6e22012b423706dc273089cd699ff8e8baa277f8eb4c9b0784012c9
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.17
    ports:
      - "4008:4001"
      - "8087:8080"

  node8:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=8
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node9/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.18
    ports:
      - "4009:4001"
      - "8088:8080"

  node9:
    build:
      context: ..
      dockerfile: mixnet-test/Dockerfile
    environment:
      - NODE_ID=9
      - MIXNET_PORT=4001
      - MIXNET_PRIV_KEY=
      - MIXNET_PEERS=12D3KooWP575uKYhFjnvidYqqu9Pob3AFkUNAMCFphTpS6z3oECL@/ip4/node0/tcp/4001,12D3KooWSDqiNSbSTrNobEfEThAZR8QzQ4pAkyvupr31WPWhHbKZ@/ip4/node1/tcp/4001,12D3KooWLH2kLeR1iyeU9w5w51KKSqyDKRsYhEkpuJVyE37Vtr3w@/ip4/node2/tcp/4001,12D3KooWEuwCdXy1yce65s1pGaiB88rXB9h9sRmVgzKCKoToCYQ5@/ip4/node3/tcp/4001,12D3KooWJGSGrKwmVSQSK7hB9ULNsjAN9Rpy5bPXqN1GKXuLekUS@/ip4/node4/tcp/4001,12D3KooWDEHrtGtQHVZyEV9ijczizNR2zWxDg2NNtxmKRANAxJH2@/ip4/node5/tcp/4001,12D3KooWE4UUC1HxiDhYFwEgYCdnfYeUC6sypr1ZzwNkKHeQLK2L@/ip4/node6/tcp/4001,12D3KooWAWr8e2fJp4C9DRhuKxmmoUXZhVUR5rXZUd2Jd4QUjhfn@/ip4/node7/tcp/4001,UNKNOWN@/ip4/node8/tcp/4001
    networks:
      mixnet-network:
        ipv4_address: 172.25.0.19
    ports:
      - "4010:4001"
      - "8089:8080"

networks:
  mixnet-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
