package relay

import (
	"context"
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"testing"
	"time"

	libp2p "github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p/core/host"
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"

	"golang.org/x/crypto/chacha20poly1305"
)

func TestHandleStream_MultiRelayShowsOnlyImmediateUpstream(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	origin := newRelayTestHost(t)
	entry := newRelayTestHost(t)
	middle := newRelayTestHost(t)
	exit := newRelayTestHost(t)
	destination := newRelayTestHost(t)
	defer origin.Close()
	defer entry.Close()
	defer middle.Close()
	defer exit.Close()
	defer destination.Close()

	connectRelayTestPeers(t, ctx, origin, entry)
	connectRelayTestPeers(t, ctx, entry, middle)
	connectRelayTestPeers(t, ctx, middle, exit)
	connectRelayTestPeers(t, ctx, exit, destination)

	entrySeen := make(chan peer.ID, 1)
	middleSeen := make(chan peer.ID, 1)
	exitSeen := make(chan peer.ID, 1)
	destSeen := make(chan peer.ID, 1)
	destPayload := make(chan []byte, 1)

	circuitID := "relay-proof"
	entryKey := bytesOf(0x11, 32)
	middleKey := bytesOf(0x22, 32)
	exitKey := bytesOf(0x33, 32)

	entryHandler := NewHandler(entry, 8, 1024*1024)
	entryHandler.EnableLibp2pResourceManager(false)
	entryHandler.setCircuitKey(circuitID, entryKey)
	entry.SetStreamHandler(ProtocolID, func(s network.Stream) {
		entrySeen <- s.Conn().RemotePeer()
		entryHandler.HandleStream(s)
	})

	middleHandler := NewHandler(middle, 8, 1024*1024)
	middleHandler.EnableLibp2pResourceManager(false)
	middleHandler.setCircuitKey(circuitID, middleKey)
	middle.SetStreamHandler(ProtocolID, func(s network.Stream) {
		middleSeen <- s.Conn().RemotePeer()
		middleHandler.HandleStream(s)
	})

	exitHandler := NewHandler(exit, 8, 1024*1024)
	exitHandler.EnableLibp2pResourceManager(false)
	exitHandler.setCircuitKey(circuitID, exitKey)
	exit.SetStreamHandler(ProtocolID, func(s network.Stream) {
		exitSeen <- s.Conn().RemotePeer()
		exitHandler.HandleStream(s)
	})

	destination.SetStreamHandler(FinalProtocolID, func(s network.Stream) {
		defer s.Close()
		destSeen <- s.Conn().RemotePeer()
		payload, err := io.ReadAll(s)
		if err != nil {
			return
		}
		destPayload <- payload
	})

	payload := []byte("live-relay-forwarding-proof")
	onionPayload, err := encryptRelayTestOnion(
		payload,
		[]peer.ID{entry.ID(), middle.ID(), exit.ID()},
		destination.ID(),
		[][]byte{entryKey, middleKey, exitKey},
	)
	if err != nil {
		t.Fatalf("encrypt onion: %v", err)
	}

	frame, err := encodeRelayTestFrame(circuitID, frameVersionFullOnion, onionPayload)
	if err != nil {
		t.Fatalf("encode relay frame: %v", err)
	}

	stream, err := origin.NewStream(ctx, entry.ID(), ProtocolID)
	if err != nil {
		t.Fatalf("open origin->entry stream: %v", err)
	}
	if _, err := stream.Write(frame); err != nil {
		t.Fatalf("write relay frame: %v", err)
	}
	if err := stream.Close(); err != nil {
		t.Fatalf("close origin stream: %v", err)
	}

	if got := waitRelayPeer(t, entrySeen, "entry upstream"); got != origin.ID() {
		t.Fatalf("entry saw upstream %s, want origin %s", got, origin.ID())
	}
	if got := waitRelayPeer(t, middleSeen, "middle upstream"); got != entry.ID() {
		t.Fatalf("middle saw upstream %s, want entry %s", got, entry.ID())
	}
	if got := waitRelayPeer(t, exitSeen, "exit upstream"); got != middle.ID() {
		t.Fatalf("exit saw upstream %s, want middle %s", got, middle.ID())
	}
	if got := waitRelayPeer(t, destSeen, "destination upstream"); got != exit.ID() {
		t.Fatalf("destination saw upstream %s, want exit %s", got, exit.ID())
	}
	if got := waitRelayPayload(t, destPayload, "destination payload"); string(got) != string(payload) {
		t.Fatalf("destination payload mismatch: got %q want %q", got, payload)
	}

	report := fmt.Sprintf("# Relay Handler Live Visibility Proof\n\n"+
		"This file is generated by `go test ./mixnet/relay -run TestHandleStream_MultiRelayShowsOnlyImmediateUpstream -v`.\n\n"+
		"| Receiver | Observed remote peer |\n"+
		"| --- | --- |\n"+
		"| Entry relay | `%s` |\n"+
		"| Middle relay | `%s` |\n"+
		"| Exit relay | `%s` |\n"+
		"| Destination | `%s` |\n\n"+
		"Result: each relay saw only its immediate upstream neighbor on the live forwarded stream, and the destination received the payload `%s`.\n",
		origin.ID(), entry.ID(), middle.ID(), exit.ID(), string(payload))
	if err := os.WriteFile("LIVE_VISIBILITY_PROOF.md", []byte(report), 0o644); err != nil {
		t.Fatalf("write live visibility proof: %v", err)
	}
}

func newRelayTestHost(t *testing.T) host.Host {
	t.Helper()
	h, err := libp2p.New(
		libp2p.ListenAddrStrings("/ip4/127.0.0.1/tcp/0"),
		libp2p.DisableRelay(),
	)
	if err != nil {
		t.Fatalf("new host: %v", err)
	}
	return h
}

func connectRelayTestPeers(t *testing.T, ctx context.Context, src host.Host, dst host.Host) {
	t.Helper()
	if err := src.Connect(ctx, peer.AddrInfo{ID: dst.ID(), Addrs: dst.Addrs()}); err != nil {
		t.Fatalf("connect %s -> %s: %v", src.ID(), dst.ID(), err)
	}
}

func waitRelayPeer(t *testing.T, ch <-chan peer.ID, label string) peer.ID {
	t.Helper()
	select {
	case id := <-ch:
		return id
	case <-time.After(5 * time.Second):
		t.Fatalf("timeout waiting for %s", label)
		return ""
	}
}

func waitRelayPayload(t *testing.T, ch <-chan []byte, label string) []byte {
	t.Helper()
	select {
	case payload := <-ch:
		return payload
	case <-time.After(5 * time.Second):
		t.Fatalf("timeout waiting for %s", label)
		return nil
	}
}

func bytesOf(b byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = b
	}
	return out
}

func encryptRelayTestOnion(payload []byte, hops []peer.ID, dest peer.ID, hopKeys [][]byte) ([]byte, error) {
	if len(hops) != len(hopKeys) {
		return nil, fmt.Errorf("hop/key mismatch")
	}
	current := payload
	for i := len(hops) - 1; i >= 0; i-- {
		isFinal := byte(0)
		nextHop := ""
		if i == len(hops)-1 {
			isFinal = 1
			nextHop = dest.String()
		} else {
			nextHop = hops[i+1].String()
		}
		plain, err := buildRelayTestHopPayload(isFinal, nextHop, current)
		if err != nil {
			return nil, err
		}
		enc, err := encryptRelayTestHopPayload(hopKeys[i], plain)
		if err != nil {
			return nil, err
		}
		current = enc
	}
	return current, nil
}

func buildRelayTestHopPayload(isFinal byte, nextHop string, payload []byte) ([]byte, error) {
	if len(nextHop) > 65535 {
		return nil, fmt.Errorf("next hop too long")
	}
	header := make([]byte, 1+2+len(nextHop))
	header[0] = isFinal
	binary.LittleEndian.PutUint16(header[1:3], uint16(len(nextHop)))
	copy(header[3:], []byte(nextHop))
	return append(header, payload...), nil
}

func encryptRelayTestHopPayload(key []byte, payload []byte) ([]byte, error) {
	if len(key) != 32 {
		return nil, fmt.Errorf("invalid hop key length")
	}
	aead, err := chacha20poly1305.NewX(key)
	if err != nil {
		return nil, err
	}
	nonce := make([]byte, nonceSize)
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, err
	}
	return append(nonce, aead.Seal(nil, nonce, payload, nil)...), nil
}

func encodeRelayTestFrame(circuitID string, version byte, payload []byte) ([]byte, error) {
	if len(circuitID) == 0 || len(circuitID) > 255 {
		return nil, fmt.Errorf("invalid circuit id")
	}
	header := make([]byte, 1+len(circuitID)+1+4)
	header[0] = byte(len(circuitID))
	copy(header[1:], []byte(circuitID))
	header[1+len(circuitID)] = version
	binary.LittleEndian.PutUint32(header[1+len(circuitID)+1:], uint32(len(payload)))
	return append(header, payload...), nil
}
