name: Go Checks

on:
  pull_request:
  push:
    branches: ["master","release-v018","release-v022","release-v023","release-v026","release-v027","release-v028","release-v029"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-check:
    uses: pl-strflt/uci/.github/workflows/go-check.yml@v0.0
