name: Go Test

on:
  pull_request:
  push:
    branches: ["master","release-v018","release-v022","release-v023","release-v026","release-v027","release-v028","release-v029","release-v030","release-v031","release-v032","release-v033"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    uses: ipdxco/unified-github-workflows/.github/workflows/go-test.yml@v1.0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
