{
 "title": "go-libp2p EventBus",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Events Types emitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(libp2p_eventbus_events_emitted_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Event Subscribers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "libp2p_eventbus_subscribers_total{instance=~\"$instance\"}",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Events emitted By Subscriber",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(libp2p_eventbus_subscriber_event_queued{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  },
  {
   "title": "Subscriber Queue Length",
   "type": "timeseries",
   "description": "Event Subscribers need to consume events quickly enough, otherwise they risk stalling the libp2p process.\nSubscribers use a buffered channel to catch temporary bursts. A queue length that doesn't return to 0 might be indicative of a problem.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "libp2p_eventbus_subscriber_queue_length{instance=~\"$instance\"}",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  },
  {
   "title": "Subscriber Queue Full",
   "type": "state-timeline",
   "description": "When the subscriber event queue fills up, it blocks the libp2p process. This can be mitigated by\n1. consuming events quickly enough on the subscriber side\n2. using a large enough buffer to absorb bursts",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "libp2p_eventbus_subscriber_queue_full{instance=~\"$instance\"}",
     "legendFormat": "{{subscriber_name}}"
    }
   ]
  }
 ]
}